package com.myexample;

import com.myexample.*;
import java.util.List;
import java.util.ArrayList;
import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cart implements Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "customer")
	private Customer customer;
	@org.kie.api.definition.type.Label(value = "cart items")
	private java.util.List<CartItem> cartItems = new ArrayList<CartItem>();
	@org.kie.api.definition.type.Label(value = "discount")
	private double discount;

	public Cart() {
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public List<CartItem> getCartItems() {
		return this.cartItems;
	}

	public void setCartItems(List<CartItem> cartItems) {
		this.cartItems = cartItems;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public Cart(Customer customer,
			List<CartItem> cartItems, double discount) {
		this.customer = customer;
		this.cartItems = cartItems;
		this.discount = discount;
	}

}