package com.myexample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CartItem implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CartItem() {
    }




}